'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property amazonas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("amazonas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property andina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("andina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atlantico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atlantico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property atlantico1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("atlantico1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property BD() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BD", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bolivar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bolivar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formada por tierras bajas, en su mayoría se extiende desde las estribaciones de las cordilleras Occidental y
        '''Central hasta las playas del mar caribe y desde el noreste del Golfo de Urabá hasta la península de la Guajira.
        '''
        '''Tiene una extención aproximada de 130.000 km cuadrados.
        ''' 
        '''Comprende 7 departamentos: 
        '''	La Guajira. 
        '''	Magdalena.
        '''	El Cesar.
        '''	Atlántico.
        '''	Bolivar.
        '''	Sucre.
        '''	Córdoba..
        '''</summary>
        Friend ReadOnly Property caribe() As String
            Get
                Return ResourceManager.GetString("caribe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cesar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cesar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cordoba() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cordoba", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property departamentos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("departamentos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property guajira() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("guajira", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La Amazonía comprende extensas regiones selváticas del oriente y sur del país 
        '''con una superficie de 400.000 km cuadrados. 
        '''
        '''Está enmarcada por la cordillera de los Andes al occidente y se extiende hacia 
        '''el oriente hasta los límites con el Brasil y Venezuela; de norte a sur se extiende 
        '''desde el río Guaviare hasta el Putumayo y el Amazonas. 
        '''
        '''Comprende tierras de los departamentos de:
        '''	Putumayo
        '''	Caquetá
        '''	Guaviare
        '''	Vaupés
        '''	Guainía
        '''	Amazonas..
        '''</summary>
        Friend ReadOnly Property info_amazonas() As String
            Get
                Return ResourceManager.GetString("info_amazonas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La región tiene este nombre porque está formada por las tres cordilleras de los Andes.
        '''
        '''Comprende tanto las montañas como los valles interandinos en una superficie aproximada 
        '''a los 305.000 km cuadrados y se extiende desde los límites con Ecuador hasta las 
        '''estribaciones de las cordilleras en la llanura del Atlántico y de occidente a oriente
        '''del flanco externo de la cordillera Occidental al flanco externo de la cordillera Oriental.
        '''
        '''Comprende los departamentos de:
        '''	Huila.
        '''	Tolima
        '''	Cundinamarca
        '''	B [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property info_andina() As String
            Get
                Return ResourceManager.GetString("info_andina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Es una inmensa sabana conocida con el nombre de Llanos Orientales.
        '''
        '''Se extiende con una superficie de 240.000 km cuadrados desde las estribaciones
        '''de la cordillera Oriental hasta el río Orinoco y desde el río Arauca hasta el 
        '''Guaviare. 
        '''
        '''Comprende las tierras de los departamentos de:
        '''	Meta
        '''	Aráuca
        '''	Casanare
        '''	Vichada..
        '''</summary>
        Friend ReadOnly Property info_orinoquia() As String
            Get
                Return ResourceManager.GetString("info_orinoquia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se encuentra entre la cordillera Occidental y el Océano Pacífico. 
        '''
        '''Posee una superficie total aproximada a los 90.000 km cuadrados. 
        '''
        '''Se extiende desde Panamá y el Golfo de Urabá hasta el riachuelo Mataje en la frontera con el Ecuador.
        '''
        '''Pertenecen a esta región los departamentos de:
        '''	Chocó
        '''	Valle del Cauca
        '''	Cauca
        '''	Nariño..
        '''</summary>
        Friend ReadOnly Property info_pacifico() As String
            Get
                Return ResourceManager.GetString("info_pacifico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property magdalena() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("magdalena", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pacifica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pacifica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property region_caribe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("region_caribe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Regiones_naturales_de_Colombia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Regiones_naturales_de_Colombia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rorinoquia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rorinoquia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to nuevo string .
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property sucre() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("sucre", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property video_atlantico() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("video_atlantico", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property video_bolivar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("video_bolivar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property video_caribe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("video_caribe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property video_cesar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("video_cesar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property video_cordoba() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("video_cordoba", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property video_guajira() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("video_guajira", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property video_magdalena() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("video_magdalena", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property video_sucre() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("video_sucre", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
